### ISSUE TITLE
It fails(

### ISSUE THREAD

**Issue by hardW** [yoshimkd/swift-auto-diagram#12]
``/.../swift-auto-diagram-master/rubyResources/helpers.rb:6:in `read': Is a directory @ io_fread - /...//Pods/R.swift (Errno::EISDIR)
	from /.../swift-auto-diagram-master/rubyResources/helpers.rb:6:in `block in entitiesFromFiles'
	from /.../swift-auto-diagram-master/rubyResources/helpers.rb:5:in `each'
	from /.../swift-auto-diagram-master/rubyResources/helpers.rb:5:in `entitiesFromFiles'
	from generateEntityDiagram.rb:61:in `<main>'``

**Comment by yoshimkd** [comment]
Could you try to run it on a smaller portion of your code (preferably without pods)?
